### ISSUE TITLE
Unable to create NvStreamMux

### ISSUE THREAD

**Issue by qnihat** [bharath5673/Deepstream#2]
I just install everthying as discribed on paper (tensorRT, deepstream 6.1, cuda and cudnn libs) but this error comes: 

Unable to create NvStreamMux 
Traceback (most recent call last):
  File "deepstream-yolo.py", line 538, in <module>
    sys.exit(main(sys.argv))
  File "deepstream-yolo.py", line 405, in main
    pipeline.add(streammux)
TypeError: Argument 1 does not allow None as a value

**Comment by bharath5673** [comment]
> I just install everthying as discribed on paper (tensorRT, deepstream 6.1, cuda and cudnn libs) but this error comes:
> 
> Unable to create NvStreamMux Traceback (most recent call last): File "deepstream-yolo.py", line 538, in sys.exit(main(sys.argv)) File "deepstream-yolo.py", line 405, in main pipeline.add(streammux) TypeError: Argument 1 does not allow None as a value

try to input valid file
or
try to delete previous deepstream.engine file.. and generate new one and run..// this may work this time.
