### ISSUE TITLE
Step 10: Running yolo.py Error

### ISSUE THREAD

**Issue by stepstep123** [bharath5673/Deepstream#3]
thanks your great job. i followed your step(yolo5n) and get some problem.

from step1 to step9. everything is great.

### step8 deepstream-app -c deepstream_app_config.txt 
**PERF:  FPS 0 (Avg)
**PERF:  0.00 (0.00)
** INFO: <bus_callback:194>: Pipeline ready

** INFO: <bus_callback:180>: Pipeline running

**PERF:  260.93 (260.91)
** INFO: <bus_callback:217>: Received EOS. Exiting ...

Quitting
App run successful.

### Step 10: Running yolo.py

root@3c38dad9654b:/opt/nvidia/deepstream/deepstream-6.1/DeepStream-Yolo# python3 deepstream-yolo.py file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4
deepstream-yolo.py:387: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
Creating Pipeline

Creating streamux

Creating source_bin  0

Creating source bin
source-bin-00
Creating Pgie

Creating tiler

Creating nvvidconv

Creating nvosd

Creating EGLSink

Adding elements to Pipeline

Linking elements in the Pipeline

deepstream-yolo.py:514: PyGIDeprecationWarning: GObject.MainLoop is deprecated; use GLib.MainLoop instead
  loop = GObject.MainLoop()
Now playing...
1 :  file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4
Starting pipeline

WARNING: [TRT]: CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
Deserialize yoloLayer plugin: yolo
WARNING: [TRT]: TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.4.0
WARNING: [TRT]: TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.4.0
WARNING: [TRT]: CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
0:00:05.177224055 21150      0x3209060 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1900> [UID = 1]: deserialized trt engine from :/opt/nvidia/deepstream/deepstream-6.1/DeepStream-Yolo/model_b1_gpu0_fp32.engine
INFO: ../nvdsinfer/nvdsinfer_model_builder.cpp:610 [Implicit Engine Info]: layers num: 5
0   INPUT  kFLOAT data            3x640x640
1   OUTPUT kFLOAT num_detections  1
2   OUTPUT kFLOAT detection_boxes 25200x4
3   OUTPUT kFLOAT detection_scores 25200
4   OUTPUT kFLOAT detection_classes 25200

0:00:05.236333287 21150      0x3209060 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2003> [UID = 1]: Use deserialized engine model: /opt/nvidia/deepstream/deepstream-6.1/DeepStream-Yolo/model_b1_gpu0_fp32.engine
0:00:05.601797793 21150      0x3209060 INFO                 nvinfer gstnvinfer_impl.cpp:328:notifyLoadModelStatus:<primary-inference> [UID 1]: Load new model:config_infer_primary_yoloV5.txt sucessfully
Decodebin child added: source

Decodebin child added: decodebin0

Decodebin child added: qtdemux0

Decodebin child added: multiqueue0

Decodebin child added: h264parse0

Decodebin child added: capsfilter0

Decodebin child added: aacparse0

Decodebin child added: avdec_aac0

Decodebin child added: nvv4l2decoder0

In cb_newpad

gstname= video/x-raw
features= <Gst.CapsFeatures object at 0x7ff4c2cb77c0 (GstCapsFeatures at 0x7ff3bc00acc0)>
In cb_newpad

gstname= audio/x-raw
0:00:06.783651849 21150      0x18e4d80 WARN                 nvinfer gstnvinfer.cpp:2299:gst_nvinfer_output_loop:<primary-inference> error: Internal data stream error.
0:00:06.783783685 21150      0x18e4d80 WARN                 nvinfer gstnvinfer.cpp:2299:gst_nvinfer_output_loop:<primary-inference> error: streaming stopped, reason not-negotiated (-4)
Error: gst-stream-error-quark: Internal data stream error. (1): gstnvinfer.cpp(2299): gst_nvinfer_output_loop (): /GstPipeline:pipeline0/GstNvInfer:primary-inference:
streaming stopped, reason not-negotiated (-4)
Exiting app

Thank you for any kind of help. I will appreciate very much.

**Comment by bharath5673** [comment]
hi @stepstep123 .. may i know your device config // gpu-info ?

**Comment by stepstep123** [comment]
> 

@bharath5673  thanks your reply
### envs:
deepstream-app version 6.1.0
DeepStreamSDK 6.1.0
Driver Version 515.65
CUDA 11.6

**Comment by bharath5673** [comment]
> > 
> 
> @bharath5673 thanks your reply
> 
> ### envs:
> deepstream-app version 6.1.0 DeepStreamSDK 6.1.0 Driver Version 515.65 CUDA 11.6

i got that,, are u running gtx1050 series graphics card ?
this is due to display drivers issue and still there is no fix for few drivers from NVIDIA too

these below links may help you :
[https://forums.developer.nvidia.com/t/blank-screen-black-while-running-the-deepstream-app-for-trafficcamnet-in-samples-configs-tlt-pretrained-models/172977/5](https://forums.developer.nvidia.com/t/blank-screen-black-while-running-the-deepstream-app-for-trafficcamnet-in-samples-configs-tlt-pretrained-models/172977/5)
[https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_troubleshooting.html](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_troubleshooting.html)
