### ISSUE TITLE
yolo-Tracker for mp4 and RTSP

### ISSUE THREAD

**Issue by deepti-pushpak** [bharath5673/Deepstream#7]
Hi,

Firstly, thank you very much for this powerful repository with concise step-by-step instructions. 
All the commands run flawlessly and I am able to implement Yolov5 detection on Jetson Xavier. The FPS is amazing.

I am also able to implement the **yolo-Tracker.py** given is Step 11 of https://gist.github.com/bharath5673/800a18cc7474ce9c22fda6deaaa98354/

I would like to put forth one gentle request. The yolo-Tracker requires .h264 as mentioned in Step 11. 
Can I also use it directly on an RTSP or .mp4?
If yes, please suggest the configuration changes that I need to do to achieve the same.
When I tried the mp4 video file, it threw an error and exited the program.

Thank you once again!

**Comment by bharath5673** [comment]
> Hi,
> 
> Firstly, thank you very much for this powerful repository with concise step-by-step instructions. All the commands run flawlessly and I am able to implement Yolov5 detection on Jetson Xavier. The FPS is amazing.
> 
> I am also able to implement the **yolo-Tracker.py** given is Step 11 of https://gist.github.com/bharath5673/800a18cc7474ce9c22fda6deaaa98354/
> 
> I would like to put forth one gentle request. The yolo-Tracker requires .h264 as mentioned in Step 11. Can I also use it directly on an RTSP or .mp4? If yes, please suggest the configuration changes that I need to do to achieve the same. When I tried the mp4 video file, it threw an error and exited the program.
> 
> Thank you once again!

yup @deepti-pushpak [deepstream-yolo-track.py](https://github.com/bharath5673/Deepstream/blob/main/deepstream-yolo-track.py)'s pipeline is entirely different. u cannot run mp4 in that..

u need to change GstElememts to run ur mp4..
try [deepstream-yolo.py](https://github.com/bharath5673/Deepstream/blob/main/deepstream-yolo.py)

and to run trackers try to integrate tracker pipeline within that  // **pgie > tracker > tiler > nvvidconv > nvosd**
