### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by anchalgupta2412** [bharath5673/Deepstream#8]
![image](https://user-images.githubusercontent.com/40071093/212937757-9ec560a1-b184-4e7d-baf1-8d161eaa4967.png)
Getting error while running deepstream-app -c deepstream_app_config_yolo.txt

Other repository is working fine.
Can you please help here?

**Comment by bharath5673** [comment]
rebooting ur system and running againg may fix ur problem :o

**Comment by bharath5673** [comment]
> ![image](https://user-images.githubusercontent.com/40071093/212937757-9ec560a1-b184-4e7d-baf1-8d161eaa4967.png) Getting error while running deepstream-app -c deepstream_app_config_yolo.txt
> 
> Other repository is working fine. Can you please help here?

rebooting ur system and running againg may fix ur problem :o
