### ISSUE TITLE
INT8 calibration

### ISSUE THREAD

**Issue by Alberto1404** [bharath5673/Deepstream#9]
Hi, 
How can we get a Tensor RT file (.engine) exported with int8 precision? It is important as with fp16 I get too low FPS. Thanks in advance.

**Comment by bharath5673** [comment]
> Hi, How can we get a Tensor RT file (.engine) exported with int8 precision? It is important as with fp16 I get too low FPS. Thanks in advance.

to generate them here u can follow these steps @ https://github.com/marcoslucianops/DeepStream-Yolo#int8-calibration
importance: it depands on ur use case..

**Comment by Alberto1404** [comment]
@bharath5673 that repo uses wts and cfg files with that precision, not onnx.

**Comment by bharath5673** [comment]
> 

Yes.. It uses wts and cfg.. But y onnx here?
